# Generated by Django 2.1.2 on 2018-11-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrcPassBreaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dictionary',
            new_name='Word',
        ),
    ]
