# Generated by Django 2.1.2 on 2018-11-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrcPassBreaker', '0002_auto_20181113_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='items',
        ),
        migrations.AddField(
            model_name='word',
            name='item',
            field=models.CharField(default='', max_length=255),
        ),
    ]
