# Generated by Django 2.1.2 on 2018-11-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrcPassBreaker', '0003_auto_20181113_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
